/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ApeDropFacetInterface extends utils.Interface {
  functions: {
    "apeMintTo(address,uint64)": FunctionFragment;
    "apePresaleActive()": FunctionFragment;
    "apePresaleMintTo(address,uint64,uint256,bytes32[])": FunctionFragment;
    "apePrice()": FunctionFragment;
    "apeRevenue()": FunctionFragment;
    "apeSaleActive()": FunctionFragment;
    "apeStartSale(uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "apeStopSale()": FunctionFragment;
    "apeWithdraw()": FunctionFragment;
    "finalizeApeDrop()": FunctionFragment;
    "initializeApeDrop(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "apeMintTo"
      | "apePresaleActive"
      | "apePresaleMintTo"
      | "apePrice"
      | "apeRevenue"
      | "apeSaleActive"
      | "apeStartSale"
      | "apeStopSale"
      | "apeWithdraw"
      | "finalizeApeDrop"
      | "initializeApeDrop"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "apeMintTo",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "apePresaleActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "apePresaleMintTo",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "apePrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "apeRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "apeSaleActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "apeStartSale",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "apeStopSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "apeWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeApeDrop",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeApeDrop",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "apeMintTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "apePresaleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "apePresaleMintTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "apePrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "apeRevenue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "apeSaleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "apeStartSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "apeStopSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "apeWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeApeDrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeApeDrop",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "ConsecutiveTransfer(uint256,uint256,address,address)": EventFragment;
    "OwnershipHandoverCanceled(address)": EventFragment;
    "OwnershipHandoverRequested(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RolesUpdated(address,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConsecutiveTransfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipHandoverCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipHandoverRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  approved: string;
  tokenId: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface ApprovalForAllEventObject {
  owner: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface ConsecutiveTransferEventObject {
  fromTokenId: BigNumber;
  toTokenId: BigNumber;
  from: string;
  to: string;
}
export type ConsecutiveTransferEvent = TypedEvent<
  [BigNumber, BigNumber, string, string],
  ConsecutiveTransferEventObject
>;

export type ConsecutiveTransferEventFilter =
  TypedEventFilter<ConsecutiveTransferEvent>;

export interface OwnershipHandoverCanceledEventObject {
  pendingOwner: string;
}
export type OwnershipHandoverCanceledEvent = TypedEvent<
  [string],
  OwnershipHandoverCanceledEventObject
>;

export type OwnershipHandoverCanceledEventFilter =
  TypedEventFilter<OwnershipHandoverCanceledEvent>;

export interface OwnershipHandoverRequestedEventObject {
  pendingOwner: string;
}
export type OwnershipHandoverRequestedEvent = TypedEvent<
  [string],
  OwnershipHandoverRequestedEventObject
>;

export type OwnershipHandoverRequestedEventFilter =
  TypedEventFilter<OwnershipHandoverRequestedEvent>;

export interface OwnershipTransferredEventObject {
  oldOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RolesUpdatedEventObject {
  user: string;
  roles: BigNumber;
}
export type RolesUpdatedEvent = TypedEvent<
  [string, BigNumber],
  RolesUpdatedEventObject
>;

export type RolesUpdatedEventFilter = TypedEventFilter<RolesUpdatedEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  tokenId: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface ApeDropFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ApeDropFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    apeMintTo(
      recipient: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    apePresaleActive(overrides?: CallOverrides): Promise<[boolean]>;

    apePresaleMintTo(
      recipient: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      allowed: PromiseOrValue<BigNumberish>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    apePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    apeRevenue(overrides?: CallOverrides): Promise<[BigNumber]>;

    apeSaleActive(overrides?: CallOverrides): Promise<[boolean]>;

    apeStartSale(
      newMaxAmount: PromiseOrValue<BigNumberish>,
      newMaxPerMint: PromiseOrValue<BigNumberish>,
      newMaxPerWallet: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      presale: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    apeStopSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    apeWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    finalizeApeDrop(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initializeApeDrop(
      tokenAddress_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  apeMintTo(
    recipient: PromiseOrValue<string>,
    quantity: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  apePresaleActive(overrides?: CallOverrides): Promise<boolean>;

  apePresaleMintTo(
    recipient: PromiseOrValue<string>,
    quantity: PromiseOrValue<BigNumberish>,
    allowed: PromiseOrValue<BigNumberish>,
    proof: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  apePrice(overrides?: CallOverrides): Promise<BigNumber>;

  apeRevenue(overrides?: CallOverrides): Promise<BigNumber>;

  apeSaleActive(overrides?: CallOverrides): Promise<boolean>;

  apeStartSale(
    newMaxAmount: PromiseOrValue<BigNumberish>,
    newMaxPerMint: PromiseOrValue<BigNumberish>,
    newMaxPerWallet: PromiseOrValue<BigNumberish>,
    newPrice: PromiseOrValue<BigNumberish>,
    presale: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  apeStopSale(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  apeWithdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  finalizeApeDrop(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initializeApeDrop(
    tokenAddress_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    apeMintTo(
      recipient: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    apePresaleActive(overrides?: CallOverrides): Promise<boolean>;

    apePresaleMintTo(
      recipient: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      allowed: PromiseOrValue<BigNumberish>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    apePrice(overrides?: CallOverrides): Promise<BigNumber>;

    apeRevenue(overrides?: CallOverrides): Promise<BigNumber>;

    apeSaleActive(overrides?: CallOverrides): Promise<boolean>;

    apeStartSale(
      newMaxAmount: PromiseOrValue<BigNumberish>,
      newMaxPerMint: PromiseOrValue<BigNumberish>,
      newMaxPerWallet: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      presale: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    apeStopSale(overrides?: CallOverrides): Promise<void>;

    apeWithdraw(overrides?: CallOverrides): Promise<void>;

    finalizeApeDrop(overrides?: CallOverrides): Promise<void>;

    initializeApeDrop(
      tokenAddress_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      approved?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter;
    Approval(
      owner?: PromiseOrValue<string> | null,
      approved?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter;

    "ApprovalForAll(address,address,bool)"(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "ConsecutiveTransfer(uint256,uint256,address,address)"(
      fromTokenId?: PromiseOrValue<BigNumberish> | null,
      toTokenId?: null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): ConsecutiveTransferEventFilter;
    ConsecutiveTransfer(
      fromTokenId?: PromiseOrValue<BigNumberish> | null,
      toTokenId?: null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): ConsecutiveTransferEventFilter;

    "OwnershipHandoverCanceled(address)"(
      pendingOwner?: PromiseOrValue<string> | null
    ): OwnershipHandoverCanceledEventFilter;
    OwnershipHandoverCanceled(
      pendingOwner?: PromiseOrValue<string> | null
    ): OwnershipHandoverCanceledEventFilter;

    "OwnershipHandoverRequested(address)"(
      pendingOwner?: PromiseOrValue<string> | null
    ): OwnershipHandoverRequestedEventFilter;
    OwnershipHandoverRequested(
      pendingOwner?: PromiseOrValue<string> | null
    ): OwnershipHandoverRequestedEventFilter;

    "OwnershipTransferred(address,address)"(
      oldOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      oldOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RolesUpdated(address,uint256)"(
      user?: PromiseOrValue<string> | null,
      roles?: PromiseOrValue<BigNumberish> | null
    ): RolesUpdatedEventFilter;
    RolesUpdated(
      user?: PromiseOrValue<string> | null,
      roles?: PromiseOrValue<BigNumberish> | null
    ): RolesUpdatedEventFilter;

    "Transfer(address,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;
  };

  estimateGas: {
    apeMintTo(
      recipient: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    apePresaleActive(overrides?: CallOverrides): Promise<BigNumber>;

    apePresaleMintTo(
      recipient: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      allowed: PromiseOrValue<BigNumberish>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    apePrice(overrides?: CallOverrides): Promise<BigNumber>;

    apeRevenue(overrides?: CallOverrides): Promise<BigNumber>;

    apeSaleActive(overrides?: CallOverrides): Promise<BigNumber>;

    apeStartSale(
      newMaxAmount: PromiseOrValue<BigNumberish>,
      newMaxPerMint: PromiseOrValue<BigNumberish>,
      newMaxPerWallet: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      presale: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    apeStopSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    apeWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    finalizeApeDrop(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initializeApeDrop(
      tokenAddress_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    apeMintTo(
      recipient: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    apePresaleActive(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    apePresaleMintTo(
      recipient: PromiseOrValue<string>,
      quantity: PromiseOrValue<BigNumberish>,
      allowed: PromiseOrValue<BigNumberish>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    apePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    apeRevenue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    apeSaleActive(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    apeStartSale(
      newMaxAmount: PromiseOrValue<BigNumberish>,
      newMaxPerMint: PromiseOrValue<BigNumberish>,
      newMaxPerWallet: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      presale: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    apeStopSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    apeWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    finalizeApeDrop(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initializeApeDrop(
      tokenAddress_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
