name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: yarn install
      - name: Run Redeemable tests
        run: yarn workspace @niftykit/contracts build && yarn workspace @niftykit/redeemable test
      - name: Run DropKit tests
        run: yarn workspace @niftykit/contracts build && yarn workspace @niftykit/dropkit test